# Generated by Django 3.0.2 on 2020-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='webaddress',
        ),
        migrations.AlterField(
            model_name='provider',
            name='ohp',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
