# Generated by Django 3.0.2 on 2020-01-22 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0002_auto_20200118_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clinics',
            new_name='departments',
        ),
    ]
