# Generated by Django 3.0.2 on 2020-01-22 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0003_auto_20200122_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departments',
            new_name='department',
        ),
    ]
