# Generated by Django 3.0.2 on 2020-01-22 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0004_auto_20200122_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('nid', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinic_id', models.IntegerField(max_length=100)),
            ],
        ),
    ]
