# Generated by Django 3.0.2 on 2020-01-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='clinic_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='department_code',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
