# Generated by Django 3.0.2 on 2020-01-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0006_auto_20200122_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
