# Generated by Django 3.0.2 on 2020-01-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0009_auto_20200123_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhcare.department'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
