# Generated by Django 3.0.2 on 2020-01-24 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0010_auto_20200124_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department_code',
        ),
    ]
