# Generated by Django 3.0.2 on 2020-01-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0011_remove_appointment_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department_code',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='dhcare.department'),
        ),
    ]
