# Generated by Django 3.0.2 on 2020-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0013_auto_20200124_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.IntegerField(default='100', primary_key=True, serialize=False, unique=True),
        ),
    ]
