# Generated by Django 3.0.2 on 2020-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0014_auto_20200124_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department_code',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
