# Generated by Django 3.0.2 on 2020-01-24 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dhcare', '0015_auto_20200124_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
